In [ ]:
환경구축 (세팅)

아나콘다
파이참(커뮤티티)

In [ ]:
편집도구

메모장
vl editor
sublime text
atom
pycham
visual studio code


In [ ]:
데이터

In [ ]:
피쳐의 개념 feature 특징
-특성이나 특징이라는 의미
 모델을 구성하는데 데이터가 가장 큰 영향을 줌
모델은 함수 형태로 표현
y=ax+b
 x,y를 주고 알고리즘을 통해 a,b 최적값을 찾음

In [ ]:
데이터테이블 data table 데이터를 테이플(표)로 표현한 것

피쳐는 데이터 테이블 상에서 하나의 열 이름 column name에 해당

데이터 인스턴스 data instance : 하나의 데이터
    튜플 이라고도 부름
    엑셀에서의 한줄 한줄 
    
행row:데이터인스턴스    
열column:피쳐

행렬의곱으 가로/세로로 곱해야한다
행렬 matrix

In [ ]:
차원의저주
 실제 머신러닝에서는 피쳐의 개수가 크게 증가하고 이게 따라 데이터를 확보해야 모델 성능을 갖출 수 있음
 차원이 늘어나면 우리가 상상하거나 표현할 수 없게 됨
 (차원의수=feature의수)

 피쳐의개수가 증가하게되면데이터를표현해야하는공간이지속적으로늘어나게되고이에대한처리가어렵게되는것
 희박한벡터생성:벡터공간에너무많은영이포함된형태로값이없는벡터들이증가하여모델전체의정확도를떨어뜨림
 데이터처리속도와메모리공간문제:셈플데이터가너무많아져문제발생
 



In [ ]:
스케일 연속적데이터
<> 이산형데이터

In [ ]:
이산형데이터의분류 : 숫자형 명목형 서수형

In [ ]:
데이터의형식
 csv (comma separate value) 파일  /  xlsx파일
 트리형태: json . xml

In [ ]:
넘파이

In [ ]:
기게학습에서는파이썬의기본리스트로충분하지않다
데이터를처리할떄는리스트와리스트간의연산이가능해야하는데파이썬의기본리스트는이것을지원하지않기때문이다
연산속도도중요하기때문에데이터과학자들은기본리스트대신에넘파이를선호한다



In [ ]:
넘파이의개념

파이썬의고성능과학걔산용라이브러리
벡터나행렬같은선형대수의표현법을코드로처리
사실사의표준라이브러리
다차원리스트나크기가큰데이터처리에유리

특징
 과학적인계산을위해서만들어진형태
 정적할당의구성방식으로사용하기위하여만들어짐
 행렬연산특화
 일반리스트에비해빠르고메모리를효율적으로사용
 속도가빠르고메모리사용이효율적
 데이터를메모리에할당하는방식이기존과다름
 반복문을사용하지않음
 연산할떄병렬로처리
 함수를한번에많은요소에적용
 반복문없이데이터배열에대한처리를지원하여빠르고편리
 선형대수와관련된다양한기능을제공
 시시플플포트란등의언어와통합이가능

성능
 넘파이의 텐서연산의 장점
   시 와 유사한형태로 메모리를관리하면서 시와 같은 연산속도로 계산할 수 있다
   메모리 구조상 요소들이 붙어있기 때문
   파이썬의 가장큰 특징인 동적타이핑을 포기했지만 시로 구현되어 있어 배열 연산에 있어 매우큰성능적우위확보
   대용량배열연산에서넘파이가사실상표준으로사용됨

넘파이배열 ndarray : 넘파이에서 텐서데이터를 다루는 객체

텐서 tensor:선형대수의 데이터배열
  랭크에따라이름이다름

랭크
0 스칼라
1 벡터
2 행렬
3 삼차원텐서
4 

In [ ]:
#l=[1,2,3,4,5]
#l2=[1,2,3,4,5]
#print(l)
#print(type(l))

#end_l=[]
#for i in range(len(l)):
#    end_l.append(l[i]+l2[i])
#print(end_l)

import numpy as np  # as뒤 np는 넘파이의 닉네임
#a1=np.array([1,2,3,4,5])
#a2=np.array([1,2,3,4,5])
#print(a1)
#print(type(a1))
#print(l[0])
#print(a1[0])
#a3=np.array([1,2,3,4])
#print(a1+1)#벡터+스칼라 연산 (넘파이만가능)
#print(a1+a3) #에러  원소값 다름


#a_2_1=np.array([1,2,3,4,5],[1,2,3,4],[1,2,3,4,5,6]) # 리스트는 가능 넘파이는 불가능 (저차원의사이즈는
                                                  #반드시 저차원에서 결정되어야한다. 저차원의사이즈는 한번정해지면 불편, 저차원이중요하다

a_2_1=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
a_2_2=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(a_2_1+a_2_2)



In [ ]:
 텐서(선형대수의데이터배열)(밸류) : 스칼라 벡터 행렬 삼차원텐서 엔차원텐서

 스칼라 0차원    1
 1차원 벡터  [1,2]
 2차원 행렬 [[1,2],[1,2]]

 


In [ ]:
파이썬 리스트와 넘파이 배여르이 차이점
넘파이- 모든구성요소에값이존재해야함 , ( ) 밸류가 단 하나만 존재해야함 
 동적타이핑지원 x > 하나의데이터타입만 사용   [1,'1'] 불가
 데이터를메모리에연속적으로나열

데이터특징을 출력하는 요소 프로퍼티 는 디타입과 세입
  디타입은 넘파이배열의데이터타입을반환 

In [ ]:

# y=wx+b
w=np.array([[1,2,3],[1,2,3],[1,2,3],[1,2,3],[1,2,3]])
x=np.array([x,x1,x2])
b=1  #바이어스값

#y=wx+b를 행렬의 곱으로
y=w.dot(x)+b


#import numpy as np
       #어레이  밸류들을 넘파이배열화시킴

#a=np.array((1,2,3,4))
#a=np.array([1,2,3,4])
#a=np.array([1,2,3.3,4],int)
#print(a)

#넘파이어레이 밸류는 1개만 가능하다
#a=np.array(1,2,3,4)  #값 4개 x에러

import numpy as np
data=[1.2 , 2 , '3' ,4.2] #하나만스트링으로바꿔도전부스트링으로
a=np.array(data)
print(a)
print(a.dtype)   #문자열이다- 유니코드로 표시
print(a.shape)  #(4,) 1차원애 원소가 4개라는말   쉐입 차원을알수잇다
             #원소딱하나만잇으면 0차원이라 ()로 나온다

data=[[[1,2,3,4],[1,2,3,4]]]
print(data.ndim)  #최대차원
print(data.size) #원소의 수 #원소8개



In [ ]:
import numpy as np
data=[[[1,2,3,4],[1,2,3,4]]]
a=np.array(data)
print(a.ndim)  #최대차원
print(a.size) #원소의 수 #원소8개

print(a)
print(a.dtype)
print(a.itemsize) #공간확인  바이트로 






3
8
[[[1 2 3 4]
  [1 2 3 4]]]
int64
8


In [ ]:
import numpy as np
data=[[[1,2,3,4],[1,2,3,4]]]
a=np.array(data)


리쉐입
reshape 배열을 원하는 모양으로 생성 및 변형




In [ ]:
import numpy as np
x=np.array([[1,2,5,8],[1,3,5,8]])
print(x.shape) # 차원조회  (2,4)
print()
print(x.reshape(-1,2))   #배열변형
print()  
print(x.reshape(2,-1).shape)  # -1 은 전체원소라는 뜻 ~ 전체원소중 어느것이라도 될 수 있다
print()
print(x.reshape(-1).shape) # 고차원은전체 저차원은 ?
print()
print(x.reshape(-1,2).shape)  # 저차원이 2개  고차원은 전체
print()
print(x.reshape(1,-1).shape)
print()
print(x.reshape(-1,1).shape)
print()
print(x.reshape(-1,2,2).shape)  # 2곱2곱2는 8개      저차원 2 2 는 정해지고  고차원 -1은 남은 것 담기
print()
print(x.reshape(-1,2,2,2).shape)    # 222는 명시적 표기 > 반드시 만족해야함     고차원-1 은 2곱2곱2 를 감싼 것
# print(x.reshape(-1,2,2,2,2).shape)  # 2곱2곱2곱2= 16 원소는 8개 맞지 않음 에러
print()
print(x.reshape(2,2,2,-1).shape)
print()
print(x.reshape(8,-1).shape)
print()
print()
print()
print()
import numpy as np
x=np.array([[2],[1]])
print(x.reshape(2,-1).shape)
print(x.reshape(2,-1))
print()
print(x.reshape(2,1,-1))     # -1은 하나만 들어갈수잇다


(2, 4)

[[1 2]
 [5 8]
 [1 3]
 [5 8]]

(2, 4)

(8,)

(4, 2)

(1, 8)

(8, 1)

(2, 2, 2)

(1, 2, 2, 2)

(2, 2, 2, 1)

(8, 1)




(2, 1)
[[2]
 [1]]

[[[2]]

 [[1]]]


In [ ]:
import numpy as np
x=np.array([[1,2,5,8],[1,3,5,8]])
x_data=np.array([1,2,3,4,5,6,7,8,9]) #원소9개
#에러   x_data.reshape(2,-1)  #원소9개를 두칸으로 나눌 수 없음
print(x_data.reshape(3,-1))
print(x_data.reshape(3,-1).shape)

t_x=x_data.reshape(9,-1)
print()
print(t_x)
print()
print(t_x.flatten())      #1차원으로 바꾸기  
print(t_x.reshape(-1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]






In [ ]:
import numpy as np


x=np.array([[1,2,3],[4,5,6]])
print(x[0][2])
print(x[0,2]) # 위랑 같은 것

3
3


In [ ]:
import numpy as np


x=np.array(              [               [   [1,2,3] , [4,5,6]  ]      ,    [ [1,2,3],[4,5,6]   ]            ]                    )
print(x[0][1])
print(x[0,1,1]) #5

x[0,0,1]=10
print(x)

#이뮤터블
#슬라이싱 - 새로만드는 거라 이뮤터블 객체도 가능
#슬라이싱 가능
[

[4 5 6]
5
[[[ 1 10  3]
  [ 4  5  6]]

 [[ 1  2  3]
  [ 4  5  6]]]


In [ ]:
slicing슬라이싱
    

In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x)
print()
print(x[0])
print()
print(x[0:])
print()
print(x[0:,2])  #고차원에선 0부터끝까지 저차원에선 2인덱값만
print()
print()
print()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[1 2 3 4 5]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[3 8]





In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5]])
print(x)
print()
print(x[0::2,2])     #(시작:끝:스텝)
print()
print()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]

[3 3]




In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[6,7,8,9,10]])
print(x)
print()
print(x[0::-2,2])     #(시작:끝:스텝)  # 0인덱에서 오른쪽에서 왼쪽으로 스캔 0인덱만 출력 > 0인덱2인덱
print(x[0::-2][2]) #위와같음
print()

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[3]




In [ ]:
import numpy as np
x=np.array([[[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[6,7,8,9,10]]])
print(x[0,0))  #3차원에서 두번차원벗기니 1차원데이터
print(x[0,0,0)) #값 나온다
print()

In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x[:,2:])
print()
print()
print()
print()
print()


[[ 3  4  5]
 [ 8  9 10]]







In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x[:,::2])
print()
print()
print()
print()
print()


[[ 1  3  5]
 [ 6  8 10]]







In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(x[::2,::3])
print()
print()
print()



[[ 1  4]
 [11 14]]







In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(x[::2,::3])
print()

t_d = np.array(list(range(10)))
print(t_d)

[[ 1  4]
 [11 14]]

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(x[::2,::3])
print()

t_d = np.array(range(10))
print(t_d)

[[ 1  4]
 [11 14]]

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
 

t_d = np.arange(10)
print(t_d)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
 

t_d = np.arange(1,10,2) #1부터10까지 2스텝
print(t_d)

[1 3 5 7 9]


In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
 

t_d = np.arange(1,10,2) #1부터10까지 2스텝
print(t_d)
k=np.ones(5) #일로 채우기 5개
print(k)

[1 3 5 7 9]
[1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
 
k=np.ones(5) #일로 채우기 5개
print(k)
print()
k=np.ones((5,5)) #일로 채우기 5,5개
print(k)
print()
print()
print()
k=np.ones((5,5,5)) #일로 채우기 5,5개
print(k)

[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [ ]:
# 영으로채우기 제로스

import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
 
k=np.ones(5) #일로 채우기 5개
print(k)
print()
k=np.ones((5,5)) #일로 채우기 5,5개
print(k)
print()
print()
print()
k=np.zeros((5,5,5)) #일로 채우기 5,5개
print(k)



[1. 1. 1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]



[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


AttributeError: ignored

In [ ]:
 #엠티
 
import numpy as np
x=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

print(np.empty(5,4))




TypeError: ignored

In [ ]:
#0으로된 2,3행열을 만드시오


import numpy as np
x=np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# 1~100R까지 스텝2로된 배열

print(np.arange(1,101,2))


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
print(np.zeros((5,5))+10)

[[10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10.]]


In [ ]:
넘파이

identity함수
  단위행렬(i행렬)을 생성
   매개변수n 으로 n*n단위행렬을 생성

eye함수

diag 함수


In [ ]:
uniform 함수:균등분포함수
   np.random.uniform (시작,끝,데이터수)
normal 함수 : 정규분포함수
    np.random.normal (평균,분산,데이터수)

In [ ]:
축 axis
  0 행 방향   1열 방향
  axis=0  axis=1

sum함수

sum(axis=0)
행방향 합, , , ,



In [ ]:
import numpy as np
x=np.arange(1,13).reshape(3,4)    # 3,4행렬
print(x)

end_x = np.array([x,x,x])     3,4차원인 x를 세개 감싸서  3,3,4 차원으로 만들었다

print(end_x.shape) #차원


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 3, 4)


In [ ]:
import numpy as np
x=np.arange(1,13).reshape(3,4)    # 3,4행렬
print(x)
print()
end_x = np.array([x,x,x])    # 3,4차원인 x를 세개 감싸서  3,3,4 차원으로 만들었다
print()
print(end_x.shape) #차원
print()
print(end_x.sum()) #차원
print()
print(end_x.sum(axis=0))   # 0젤 높은 차원의 축
print()
print(end_x.sum(axis=1))
print()
print(end_x.sum(axis=2))
print()
print()                           #    (3,3,4) 행렬
print()                  #     axis  (  0 1 2 ) 축방향    #숫자하나 올릴수록 차원하나 벗기고 그 기준으로 연산ㄷ
print()
print(end_x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 3, 4)

234

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]

[[15 18 21 24]
 [15 18 21 24]
 [15 18 21 24]]

[[10 26 42]
 [10 26 42]
 [10 26 42]]



[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [ ]:
 넘파이는 직접 원소데이터를 저장하기 떄문에 저차원 밸류의 크기들이 전부 같아야 한다.
 

In [142]:
import numpy as np

x=np.array([[1,2,3]])
y=np.array([[1],[2],[3]])
print(x.shape,y.shape)


(1, 3) (3, 1)


In [146]:
import numpy as np

x=np.array([[1,2,3]])
y=np.array([[1],[2],[3]])
print(x.shape,y.shape)
#x.vstack()
#print(np.vstack(x.T,y))

print(x)
print(x.T)






(1, 3) (3, 1)
[[1 2 3]]
[[1]
 [2]
 [3]]


In [149]:
import numpy as np

x=np.array([[1,2,3]])
y=np.array([[1],[2],[3]])
print(x.shape,y.shape)
# x를 세로로 돌리고 쌓기위한 

#x.vstack()
print(np.vstack((x.T,y)))

# T란 트랜스포즈

#에이치스택
print(np.hstack((x.T,y)))




(1, 3) (3, 1)
[[1]
 [2]
 [3]
 [1]
 [2]
 [3]]
[[1 1]
 [2 2]
 [3 3]]


In [ ]:
concatenate함수
축으로붇이기

In [158]:
v1=np.array([[1,2],[3,4]])
v2=np.array([[5,6]])
print(v1.shape,v2.shape)
print(np.concatenate((v1,v2))) #디폴트 엑시스=0
print(np.concatenate((v1,v2),axis=0))
#에러 print(np.concatenate((v1,v2),axis=1))

(2, 2) (1, 2)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [160]:
v1=np.array([[1,2],[3,4]])
v2=np.array([[5,6]])
print(v1.shape,v2.shape)
print(v1.shape,v2.T.shape)
print(np.concatenate((v1,v2))) #디폴트 엑시스=0
print(np.concatenate((v1,v2),axis=0))
#에러 print(np.concatenate((v1,v2),axis=1))

(2, 2) (1, 2)
(2, 2) (2, 1)
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
사칙연산함수
 넘파이는 파이썬과 동일하게 배열 간 사칙연산 지원
 행렬과 행려르 벡터와 벡터 간 사칙연산이 가능
 
 같은 배열의 구조일 때 요소별 연산
 요소별 연산: 두배열의 구조가 동일할 경우 같은 인덱스 요소들끼리 연산



In [168]:
import math

h=np.array([1.83 , 1.76 , 1.69 , 1.86 , 1.77 , 1.73])
w= np.array([ 86, 74 , 59 , 95 , 80 , 68 ])

bmi = w / h**2 
print(bmi)
print(np.trunc(bmi))

[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]
[25. 23. 20. 27. 25. 22.]
