In [ ]:
continuous data 연속형데이터
discrete data 이산형데이터

이산형데이터 : 숫자형 명목형 서수형

트리형태로저장 제이선
csv컴마세퍼밸류
파이썬 피클

넘파이/리스트
    칸 당 사이즈 같아서 인덱스 사용 가능

리스트
  값을 주소( > 값 )로 저장 > 다른타입이 담길수 있다

넘파이(배열)
  값을 직접저장 > 다른타입이 담길 수 없다

shape (행열 모양)
reshape(행,열) 행렬 변경

넘파이인덱스
 [행][열] 또는 [행,열]

 슬라이싱      [ :2 , :]    행: 0부터1까지 열: 전체
  [        행,  열          ]
  [ 시작끝스텝,시작끝스텝   ].

   넘파이-이뮤터블객체로칭한다 정적할당

컨켓함수
concatenate
축을고려해여 배열을 결함

In [ ]:
import numpy as np
x=np.array([1,2])  #1차원은 가로일차랑 세로일차랑 같게 취급됨
y=x.T #x를 트랜스포
x,y  #프로그램코드적으로는 같아보이는 것일 분  엑스는 가로 와이는 세로

(array([1, 2]), array([1, 2]))

In [ ]:
import numpy as np
x=np.array([1,2])  #1차원은 가로일차랑 세로일차랑 같게 취급됨
y=x.T #x를 트랜스포
print(x,y,sep='\n')

[1 2]
[1 2]


In [ ]:
x.shape , y.shape

((2,), (2,))

In [ ]:
import numpy as np
x=np.array([1,2])  #1차원은 가로일차랑 세로일차랑 같게 취급됨
y=np.array([1,2]).T #x를 트랜스포
x.shape , y.shape

((2,), (2,))

In [ ]:
import numpy as np
x=np.array([1,2]) 
x.shape 

(2,)

In [ ]:
곱연산은 스카라연산과 벡터연산이 있다
스칼라연산은 각각의 원소로 연산됨
벡터연산은 내적이라 부르고 가로 세로로 연산


In [ ]:
브로드캐스팅연산 (다른 행렬간의 연산 알아서확장해서 연산함)
  하나의행렬과스칼라값들 간의 연산이나 행렬과 벡터간의연산
    방송국의전파가퍼지듯뒤에있는스칼라값이모든요소에퍼지듯이연산
   
broadcasting operations



a1= np.array([[1,1,1],[1,1,1],[1,1,1]])
b1= np.array([[1,1,1]])
print(a1)
print()
print(b1)
print() 
print(a1+b1)


[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[1 1 1]]

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
a2= np.array([[1],[1],[1]])
b2= np.array([[1,1,1]])
print(a2)
print()
print(b2)
print() 
print(a2+b2)

[[1]
 [1]
 [1]]

[[1 1 1]]

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
비교연산
    연산결과는 항상 불린형을 가진 배열로 추출

    브로드캐스팅 비교 연산



In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,-1)

x>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [ ]:
ck=x>5

In [ ]:
y=np.array([1,2,3])   #[1,2]는에러 축은 하나만 늘릴 수 있어서  (축  행,열 2축을 늘려야할 땐 에러)
x>y                     # 단 [1] 단일 값은 확장이 가능하다 스칼라로 취급

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
올 함수 애니 함수

all 함수
   전부 만족해야 True      하나라도 참이 아니면 False
   

In [ ]:
data= x>y
data

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
data= x>y
np.all(data)
   

False

In [ ]:
any 함수
하나라도 참이면 True         모두거짓이라야 False

In [ ]:
data= x>y
np.any(data)

True

In [ ]:
#난수0~100 을 이용하여 백명의학생들의점수를만들고조건에맞게출력하는프로그램을만드시오


x=np.random.randint(0,101    ,100) #영에서백까지 랜덤으로  10개뽑는다      (시작,종료,몇개)

# 1. 평균이 50점이상이면 전원통과출력

print(x)
print()
print(np.mean(x))

if np.mean(x) >= 50:
    print('전원통과')

if np.all(x >= 50):               #전원50점이상일때
    print('학년1등반출력')

if np.any(x==100) :
    print('전교1등이있는반출력')  #한명이라도백점일때



[83 78  8 43 95 61 75 19  7 57 27 29 92 74 87 12  4 83 43 42 32 72  3  4
 89 26  5 24 98 34 28 87 63 60 73 22 19 30 77 71 81  8 29 14 84 49 85 91
 12 56 16 83 88 79 57 78 21  0 53 96 14 14 78 26  5  8 27 76 67 22 87 96
 77 58 35 40 66 16 53 84 94 45 79  4 91 68  6 69 85 43 25 76 32 11 89 29
  1 80 49 86]

50.27
전원통과


In [ ]:
where 함수
 배열이불린형으로이루어졋을떄참인값들의인덱스를반환
 
 (조건)
 조건이 트루인 곳의 인덱스를 묶어서 > 어레이로 알려줌

np.where ( 조건, 참인곳에넣을값, 폴스인곳에넣을값)   
 어레이에 값을 넣어줌 

조건만 걸어주면 트루인 인덱스를 어레이로 알려주고
조건,참일때값,폴스일때값
을 넣으면 그대로 그 값을 넣은 어레이로 줌


In [ ]:
x=np.array([1,2,3,4,5])
np.where(x==3,2,3)


array([3, 3, 2, 3, 3])

array([3, 4, 5, 1, 2])

In [ ]:
np.argsort(x)   #정렬

array([3, 4, 0, 1, 2])

In [ ]:
x=np.array([2,1,5,4,3])
np.argsort(x) 

# 오름차순순으로 0부터 알려줌            21543 을      1에 0   2에 1   3에 2 ~        #오름차순 순으로 인덱스값을 매겨줌

array([1, 0, 4, 3, 2])

In [ ]:
argsort
argmax
argmin

In [ ]:
불린 인덱스       불린을 인덱스로쓰겟다는뜻
 배열에있는값들을반환할특정조건을불린형의배열에넣어서추출

 x[x>3]      x어레이상 값이 3초과인 값만 꺼내서 어레이로
 

In [ ]:
np.argsort(x) ,x[np.argsort(x)]

(array([1, 0, 4, 3, 2]), array([1, 2, 3, 4, 5]))

In [ ]:
l=np.array([1,2,3,4,5,6])
#l[0,2,4,3,1] #이런식으루쓰면인덱이아니라차원을이야기하는것이라 에러
l[np.array([0,2,4,3,1])] #인덱스값으로 뽑는 법


array([1, 3, 5, 4, 2])

In [ ]:
l=np.array([1,2,3,4,5,6])              #불린인덱으로 뽑기  트루면 뽑아옴
l[np.array([True,False,True,False,True,False])]

array([1, 3, 5])

In [ ]:
x, np.argmax(x) # 맥스값인 곳에 인덱스를 추출 5> 2인덱스

(array([2, 1, 5, 4, 3]), 2)

In [ ]:
팬시 fancy인덱스
x[ ]  안에 엔피어레이구조를 넣는다 엔피어레이[1,2,3,4,6]  x의 1,2,3,4.6인덱값의 밸류를 추출
x[a,b]   a,b두개의 어레이를 사용하여   x의 a컴마b좌표의 밸류를 추출함


In [ ]:
판다스  #데이터구조

판다스란
    파이썬의데이터분석라이브러리
        데이터테이블을다루는도구

    기본적으로 넘파이를사용
        판다스는넘파이를효율적으로사용하기위해인덱싱연산전처리등다양한함수제공

데이터프레임
    데이터테이블전체객체



^^^^^^^^^^^^^^


시리즈 (판다스의 시리즈)
    각열데이터를다루는객체

  피쳐의 시리즈    피쳐의 각 열데이터를 말함   1차원의 값

시리즈객체
    일반적으로하나의피쳐데이터를포함하는형태
    생성된데이터프레임안에포함될수잇음
    리스트딕셔너리엔디어레이등다양한데이터타입이시리즈객체형태로변환되기도함

시리즈객체를생성하면세가지요소생성
    데이터
        기존다른객체처럼값을저장하는요소
        시리즈데이터하나가 하나의자료형을가져야함 시리즈하나는 같은자료형으로 구성되어야 한다
        (데이터프레임[전체데이터]는 같은자료형이아니어도 된다는말)
    인덱스
        0부터시작하고숫자로만할당하는값
        시리즈객체에서는숫자문자열영외의값으로시작하는숫자
        순서가일정하지않은숫자를입력할수도있음
        시리즈객체에서는인덱스값의중복을허용
            인덱스이름을바꿀수잇다 첫인덱도 두번쨰인덱도 인덱스1로 정할수잇다
    데이터타입
        넘파이의데이터타입과일치
        판다스는넘파이의래퍼라이브러리
        넘파이의모든기능지원하고데이터타입도그대로적용

시리즈객체는넘파이배열의하위클래스
넘파이가지원하는어떠한데이터타입도지원


In [ ]:
판다스

In [ ]:
#판다스의 선언      

#판다스는 넘파이의 하위클래스지만 연산할떄는구분하기위해 넘파이판다스둘다불러온다

import numpy as np
import pandas as pd

#판다스안에 시리즈객체의 클래스가잇다
pd.Series 

In [ ]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame    #(프롬판다스임폴시리즈/ 프로만다스임폴데이터프레임)
#시리즈(각 열)는 1차원 데이터프레임은 2차원

In [ ]:

# Series(리스트) 
Series([1,2,3,4,5])  #인덱스랑같이추출

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:

# Series(리스트) 
Series(index=[1,2,3,4,5], data=[1,2,3,4,5])   #인덱스를명시

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [ ]:

# Series(리스트) 
Series(index=[1,2,3,4,5], data=[1,2,3,4,5], dtype='float32') #데이터타입  float만쓰면 디폴트로 'float64'가 들어감 숫자는 데이트크기



1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
dtype: float32

In [ ]:

# Series(리스트) 
Series(index=['1','2','2','2','5'], data=[1,2,3,4,5])  #인덱스가 중복 가능하고 문자도 가능

1    1
2    2
2    3
2    4
5    5
dtype: int64

In [ ]:

# Series(리스트) 
Series(index=['1','2','2','2'], data=[1,2,3,4,5])  #인덱스가 중복 가능하고 문자도 가능
인덱과 데이터 수가 같지 않음- 에러

ValueError: ignored

In [ ]:

# Series(리스트) 
s = Series(index=['1','2','2','2','5'], data=[1,2,3,4,5])   

s.index.name= 'id'
s.name='data'
s

id
1    1
2    2
2    3
2    4
5    5
Name: data, dtype: int64

In [ ]:
#딕셔너리기반 시리즈만들기
s = Series(index=['a','b','c','d','e'], data=[1,2,3,4,5])   
d={'a':1,'b':2,'c':3,'d':4,'e':5,}
s2 = Series(d)
print(s)
print()
print(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int64

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
s3=Series(index=['a','b','c','d','e','f'],data=[1,2,3,4,5,6])
s3


a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [ ]:
s4= Series({'a':1,'b':2,'c':3,'d':4,'e':5},index=['a','b','c','d'])
  
s4

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
s4= Series({'a':1,'b':2,'c':3,'d':4,'e':5},index=['a','b','c','d','e','f','g'])
 # 
s4   # 뒤인덱이 길다  NaN으로 빈 칸 추가 > nan 때문에 플롯 타입으로 변경

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    NaN
g    NaN
dtype: float64

In [ ]:
s4= Series({'a':1,'b':2,'c':3,'d':4,'e':5},index=['a','b','c'])
 # 
s4    # 인덱스= 으로 명시해준 것이 기준이다

a    1
b    2
c    3
dtype: int64

In [ ]:
ss=Series([1,3,3,4,5,7],index=[1,2,3,4,5,6]) #데이터를 앞에 인덱을 뒤에넣는 경우
ss

1    1
2    3
3    3
4    4
5    5
6    7
dtype: int64

In [ ]:
데이터프레임 객체 :시리즈의 합  > 행이 아닌 시리즈/열 이 고차원이다
    데이터테이블전체를지칭하는객체
  
DataFrame(d)

In [ ]:
d={'a':1,'b':2,'c':3,'d':4,'e':5}

DataFrame(d)

ValueError: ignored

In [ ]:
d={'a':[1,2,3,4,5],'b':[1,2,3,4,5],'c':[1,2,3,4,5],'d':[1,2,3,4,5],'e':[1,2,3,4,5]}

DataFrame(d)       #이차원데이터를 줘야 만든다

a  b  c  d  e
0  1  1  1  1  1
1  2  2  2  2  2
2  3  3  3  3  3
3  4  4  4  4  4
4  5  5  5  5  5

In [ ]:
d={'a':[1,2,3,4,5],'b':[1,2,3,4,5],'c':[1,2,3,4,5],'d':[1,2,3,4,5],'e':[1,2,3,4,5]}

df=DataFrame(d)       #이차원데이터를 줘야 만든다

df['data']=[1,2,3,4,5]
df

a  b  c  d  e  data
0  1  1  1  1  1     1
1  2  2  2  2  2     2
2  3  3  3  3  3     3
3  4  4  4  4  4     4
4  5  5  5  5  5     5

In [ ]:
d={'a':[1,2,3,4,5],'b':[1,2,3,4,5],'c':[1,2,3,4,5],'d':[1,2,3,4,5],'e':[1,2,3,4,5]}

df=DataFrame(d)       #이차원데이터를 줘야 만든다

df['data']=[1,2,3,4,5,6]
df

ValueError: ignored

In [ ]:

d={'a':[1,2,3,4,5],'b':[1,2,3,4,5],'c':[1,2,3,4,5],'d':[1,2,3,4,5],'e':[1,2,3,4,5]}

df=DataFrame(d)       #이차원데이터를 줘야 만든다

df['data1']=[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]
df, df['data1']
 #시리즈자체에서는 같은타입이어야하지만 데이터프레임에서 보면 달라도 상관 없다


(   a  b  c  d  e            data1
 0  1  1  1  1  1  [1, 2, 3, 4, 5]
 1  2  2  2  2  2  [1, 2, 3, 4, 5]
 2  3  3  3  3  3  [1, 2, 3, 4, 5]
 3  4  4  4  4  4  [1, 2, 3, 4, 5]
 4  5  5  5  5  5  [1, 2, 3, 4, 5], 0    [1, 2, 3, 4, 5]
 1    [1, 2, 3, 4, 5]
 2    [1, 2, 3, 4, 5]
 3    [1, 2, 3, 4, 5]
 4    [1, 2, 3, 4, 5]
 Name: data1, dtype: object)

In [ ]:

d={'a':[1,2,3,4,5],'b':[1,2,3,4,5],'c':[1,2,3,4,5],'d':[1,2,3,4,5],'e':[1,2,3,4,5]}

df=DataFrame(d)       #이차원데이터를 줘야 만든다

df['data1']=[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],5]
df

#data1은 전부 오브젝트타입  

df['data1']

0    [1, 2, 3, 4, 5]
1    [1, 2, 3, 4, 5]
2    [1, 2, 3, 4, 5]
3    [1, 2, 3, 4, 5]
4                  5
Name: data1, dtype: object

In [ ]:
DataFrame(index=[1,2,3,4,5])    #인덱만 생성

In [176]:
DataFrame(index=[1,2,3,4,5], columns=[1,2,3,4,5])    # 인덱-행   칼럼-열

1    2    3    4    5
1  NaN  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN  NaN
4  NaN  NaN  NaN  NaN  NaN
5  NaN  NaN  NaN  NaN  NaN

In [177]:
pd.read_csv('train.csv') #트레인csv파일을 문자열로 읽겟다

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [180]:
df = pd.read_csv('train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [183]:
df = pd.read_csv('train.csv')
DataFrame(df)
DataFrame(df,columns=['Name','Sex','Age','SibSp'])

Name     Sex   Age  SibSp
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

[891 rows x 4 columns]

In [184]:
dfdf[['Name','Sex','Age','SibSp']]

Name     Sex   Age  SibSp
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

[891 rows x 4 columns]

In [ ]:
df=pd.read.csv('train.csv')
df.head(100)       #100개의데이터로 자르기   원본유지 새로만들기
           #df = df.head(100) 이면 원본 바꾸기


In [186]:
df[['Name','Sex','Age','SibSp']]

Name     Sex   Age  SibSp
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

[891 rows x 4 columns]

In [185]:
df[['Name','Sex','Age','SibSp']].head()

Name     Sex   Age  SibSp
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

In [187]:
에러
df[0]  데이터프레임은 시리즈(열) 의 합 


KeyError: ignored

In [188]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...                        
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [189]:
df['Name'][0]

'Braund, Mr. Owen Harris'

In [190]:
df[:3] # 슬라이싱을 하면 시리즈가 아니라 인덱(행) 기준으로 슬라이싱한다
      #시리즈는 순서로 구분하기 힘들어서

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [191]:
df[['Name','Sex','Age','SibSp']][:2]

Name     Sex   Age  SibSp
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1

In [192]:
df[:2][['Name','Sex','Age','SibSp']]

Name     Sex   Age  SibSp
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1

In [196]:
df.index=df['PassengerId']
df

PassengerId  Survived  Pclass  \
PassengerId                                  
1                      1         0       3   
2                      2         1       1   
3                      3         1       3   
4                      4         1       1   
5                      5         0       3   
...                  ...       ...     ...   
887                  887         0       2   
888                  888         1       1   
889                  889         0       3   
890                  890         1       1   
891                  891         0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
...                                                        ...     ...   ...   
887                                      Montvila, Rev. Juozas    male  27.0   
888                               Graham, Miss. Margaret Edith  female  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
890                                      Behr, Mr. Karl Howell    male  26.0   
891                                        Dooley, Mr. Patrick    male  32.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
...            ...    ...               ...      ...   ...      ...  
887              0      0            211536  13.0000   NaN        S  
888              0      0            112053  30.0000   B42        S  
889              1      2        W./C. 6607  23.4500   NaN        S  
890              0      0            111369  30.0000  C148        C  
891              0      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [199]:
df.index=df['PassengerId']
del df['PassengerId']
df

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
...               ...     ...   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
...                                                        ...     ...   ...   
887                                      Montvila, Rev. Juozas    male  27.0   
888                               Graham, Miss. Margaret Edith  female  19.0   
889                   Johnston, Miss. Catherine Helen "Carrie"  female   NaN   
890                                      Behr, Mr. Karl Howell    male  26.0   
891                                        Dooley, Mr. Patrick    male  32.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
...            ...    ...               ...      ...   ...      ...  
887              0      0            211536  13.0000   NaN        S  
888              0      0            112053  30.0000   B42        S  
889              1      2        W./C. 6607  23.4500   NaN        S  
890              0      0            111369  30.0000  C148        C  
891              0      0            370376   7.7500   NaN        Q  

[891 rows x 11 columns]

In [202]:
# df['Name',0]  에러
df.loc[1]

Survived                          0
Pclass                            3
Name        Braund, Mr. Owen Harris
Sex                            male
Age                            22.0
SibSp                             1
Parch                             0
Ticket                    A/5 21171
Fare                           7.25
Cabin                           NaN
Embarked                          S
Name: 1, dtype: object

In [203]:
# df['Name',0]  에러
df.loc['Name',1] 에러

KeyError: ignored

In [234]:
# df['Name',0]  에러
df.iloc[:,4]

PassengerId
1      22.0
2      38.0
3      26.0
4      35.0
5      35.0
       ... 
887    27.0
888    19.0
889     NaN
890    26.0
891    32.0
Name: Age, Length: 891, dtype: float64

In [207]:
df['a'][1]  # 시리즈가 일차원인식 그리고 내부의 원소가 값취급 [시리즈명][인덱]
# 1  1
  1   3
    네임 타입

KeyError: ignored

In [209]:
df.loc[1,'a'] #인덱스화 실값을이용  [가로][세로]
# loc 은 행을 앞에 쓰는 다른 인덱활용과 같아서 좋다

KeyError: ignored

In [210]:
df.iloc[1,'a'] #상대주소화 정수 인덱스화 (중복이없다) 넘파이기반의 인덱스화

ValueError: ignored

In [ ]:
df.iloc[0:2,0::2] #상대주소화 정수 인덱스화 (중복이없다) 넘파이기반의 인덱스화

In [212]:
df1=pd.read_csv('train.csv')
df1=df1.head(100)
df1.iloc[0::2,:]

PassengerId  Survived  Pclass  \
0             1         0       3   
2             3         1       3   
4             5         0       3   
6             7         0       1   
8             9         1       3   
10           11         1       3   
12           13         0       3   
14           15         0       3   
16           17         0       3   
18           19         0       3   
20           21         0       2   
22           23         1       3   
24           25         0       3   
26           27         0       3   
28           29         1       3   
30           31         0       1   
32           33         1       3   
34           35         0       1   
36           37         1       3   
38           39         0       3   
40           41         0       3   
42           43         0       3   
44           45         1       3   
46           47         0       3   
48           49         0       3   
50           51         0       3   
52           53         1       1   
54           55         0       1   
56           57         1       2   
58           59         1       2   
60           61         0       3   
62           63         0       1   
64           65         0       1   
66           67         1       2   
68           69         1       3   
70           71         0       2   
72           73         0       2   
74           75         1       3   
76           77         0       3   
78           79         1       2   
80           81         0       3   
82           83         1       3   
84           85         1       2   
86           87         0       3   
88           89         1       1   
90           91         0       3   
92           93         0       1   
94           95         0       3   
96           97         0       1   
98           99         1       2   

                                                 Name     Sex    Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.00      1   
2                              Heikkinen, Miss. Laina  female  26.00      0   
4                            Allen, Mr. William Henry    male  35.00      0   
6                             McCarthy, Mr. Timothy J    male  54.00      0   
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.00      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.00      1   
12                     Saundercock, Mr. William Henry    male  20.00      0   
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.00      0   
16                               Rice, Master. Eugene    male   2.00      4   
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.00      1   
20                               Fynney, Mr. Joseph J    male  35.00      0   
22                        McGowan, Miss. Anna "Annie"  female  15.00      0   
24                      Palsson, Miss. Torborg Danira  female   8.00      3   
26                            Emir, Mr. Farred Chehab    male    NaN      0   
28                      O'Dwyer, Miss. Ellen "Nellie"  female    NaN      0   
30                           Uruchurtu, Don. Manuel E    male  40.00      0   
32                           Glynn, Miss. Mary Agatha  female    NaN      0   
34                            Meyer, Mr. Edgar Joseph    male  28.00      1   
36                                   Mamee, Mr. Hanna    male    NaN      0   
38                 Vander Planke, Miss. Augusta Maria  female  18.00      2   
40     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.00      1   
42                                Kraeff, Mr. Theodor    male    NaN      0   
44                      Devaney, Miss. Margaret Delia  female  19.00      0   
46                                  Lennon, Mr. Denis    male    NaN      1   
48                                Samaan, Mr. Youssef    male    NaN      2   
50                         Panula, Master. Juha Niilo    male 

In [215]:
df1=pd.read_csv('train.csv')
df1=df1.head(100)
df1.iloc[0::2,:]

df2=df1.reset_index()          #인덱을 리셋
df2

index  PassengerId  Survived  Pclass  \
0       0            1         0       3   
1       1            2         1       1   
2       2            3         1       3   
3       3            4         1       1   
4       4            5         0       3   
..    ...          ...       ...     ...   
95     95           96         0       3   
96     96           97         0       1   
97     97           98         1       1   
98     98           99         1       2   
99     99          100         0       2   

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1   
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                              Heikkinen, Miss. Laina  female  26.0      0   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
..                                                ...     ...   ...    ...   
95                        Shorney, Mr. Charles Joseph    male   NaN      0   
96                          Goldschmidt, Mr. George B    male  71.0      0   
97                    Greenfield, Mr. William Bertram    male  23.0      0   
98               Doling, Mrs. John T (Ada Julia Bone)  female  34.0      0   
99                                  Kantor, Mr. Sinai    male  34.0      1   

    Parch            Ticket     Fare    Cabin Embarked  
0       0         A/5 21171   7.2500      NaN        S  
1       0          PC 17599  71.2833      C85        C  
2       0  STON/O2. 3101282   7.9250      NaN        S  
3       0            113803  53.1000     C123        S  
4       0            373450   8.0500      NaN        S  
..    ...               ...      ...      ...      ...  
95      0            374910   8.0500      NaN        S  
96      0          PC 17754  34.6542       A5        C  
97      1          PC 17759  63.3583  D10 D12        C  
98      1            231919  23.0000      NaN        S  
99      0            244367  26.0000      NaN        S  

[100 rows x 13 columns]

In [218]:
df2.drop(columns=['index'],inplace=True)
df2

KeyError: ignored

In [ ]:
loc 는    행숫자,'시리즈'이름
iloc     행숫자,열숫자
          :   ,   :   는 전체
