In [1]:
! pip install kss konlpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import nltk, kss, konlpy       # nltk 영어분석기   konlpy한국어분석기

In [3]:
nltk.__version__,konlpy.__version__

('3.7', '0.6.0')

In [4]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence #<토크나이저??;토큰화;잘라주는
from nltk.tokenize import word_tokenize # 토크나이저
from nltk.tokenize import WordPunctTokenizer #토크나이저

In [5]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [6]:
d="the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room titillate it so heart shows to years of every never going villaronga help moments or of every"



In [7]:
word_tokenize(d)

['the',
 'as',
 'you',
 'with',
 'out',
 'themselves',
 'powerful',
 'lets',
 'loves',
 'their',
 'becomes',
 'reaching',
 'had',
 'journalist',
 'of',
 'lot',
 'from',
 'anyone',
 'to',
 'have',
 'after',
 'out',
 'atmosphere',
 'never',
 'more',
 'room',
 'titillate',
 'it',
 'so',
 'heart',
 'shows',
 'to',
 'years',
 'of',
 'every',
 'never',
 'going',
 'villaronga',
 'help',
 'moments',
 'or',
 'of',
 'every']

In [8]:
len(word_tokenize(d))

43

In [9]:
WordPunctTokenizer().tokenize(d)  #대문자니까클래스 > 인스턴스가필요하다

['the',
 'as',
 'you',
 'with',
 'out',
 'themselves',
 'powerful',
 'lets',
 'loves',
 'their',
 'becomes',
 'reaching',
 'had',
 'journalist',
 'of',
 'lot',
 'from',
 'anyone',
 'to',
 'have',
 'after',
 'out',
 'atmosphere',
 'never',
 'more',
 'room',
 'titillate',
 'it',
 'so',
 'heart',
 'shows',
 'to',
 'years',
 'of',
 'every',
 'never',
 'going',
 'villaronga',
 'help',
 'moments',
 'or',
 'of',
 'every']

In [10]:
d='안녕하세요. 저는 강의 중 입니다'
text_to_word_sequence(d)  # 아웃풋을 보면 . 이 날아갔다

['안녕하세요', '저는', '강의', '중', '입니다']

In [11]:
d="Don't the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room titillate it so heart shows to years of every never going villaronga help moments or of every"


from nltk.tokenize import TreebankWordTokenizer
TreebankWordTokenizer().tokenize(d), word_tokenize(d), WordPunctTokenizer().tokenize(d)  #자르는 방식이 다르다 don't

(['Do',
  "n't",
  'the',
  'as',
  'you',
  'with',
  'out',
  'themselves',
  'powerful',
  'lets',
  'loves',
  'their',
  'becomes',
  'reaching',
  'had',
  'journalist',
  'of',
  'lot',
  'from',
  'anyone',
  'to',
  'have',
  'after',
  'out',
  'atmosphere',
  'never',
  'more',
  'room',
  'titillate',
  'it',
  'so',
  'heart',
  'shows',
  'to',
  'years',
  'of',
  'every',
  'never',
  'going',
  'villaronga',
  'help',
  'moments',
  'or',
  'of',
  'every'],
 ['Do',
  "n't",
  'the',
  'as',
  'you',
  'with',
  'out',
  'themselves',
  'powerful',
  'lets',
  'loves',
  'their',
  'becomes',
  'reaching',
  'had',
  'journalist',
  'of',
  'lot',
  'from',
  'anyone',
  'to',
  'have',
  'after',
  'out',
  'atmosphere',
  'never',
  'more',
  'room',
  'titillate',
  'it',
  'so',
  'heart',
  'shows',
  'to',
  'years',
  'of',
  'every',
  'never',
  'going',
  'villaronga',
  'help',
  'moments',
  'or',
  'of',
  'every'],
 ['Don',
  "'",
  't',
  'the',
  'as',


In [12]:
d2 =  "Don't the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room titillate it so heart shows to years of every never going villaronga help moments or of every"


In [13]:
d_k='안녕하십니까. 저는 오늘 강의 중입니다. 어렵나요? 보죠.'

In [14]:
#문장토큰 센트토크나이즈

In [15]:
from nltk.tokenize import sent_tokenize # 영어 토크나이저  인데 한글이되나? #이건 문장토큰  #문장토큰이라 단어토큰보다 문장토큰이 먼저발동한다
sent_tokenize(d2)                       #                                   

["Don't the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room titillate it so heart shows to years of every never going villaronga help moments or of every"]

In [16]:
sent_tokenize(d_k)

['안녕하십니까.', '저는 오늘 강의 중입니다.', '어렵나요?', '보죠.']

In [17]:
'강'.isalpha() #isalpha()알파벳이맞는지확인 영어/한글

True

In [20]:
from nltk.tokenize import word_tokenize #토크나이저로나누고 테그를들어가겟다
from nltk.tag import  pos_tag #영어분석기
from konlpy.tag import Okt, Kkma #한국어분석 한국어형태소분석기  형태소=tag
  #형태소 분석 후 형태소를 기준으로 잘라냄

In [22]:
d="Don't the as you with out themselves powerful lets loves their becomes reaching had journalist of lot from anyone to have after out atmosphere never more room titillate it so heart shows to years of every never going villaronga help moments or of every"
k_d='오늘은 인공지능 입니다. 어렵네요.'

In [23]:
n_t=word_tokenize(d)

In [24]:
pos_tag(n_t) #주어냐목적어냐를 옆에 표기함

[('Do', 'VBP'),
 ("n't", 'RB'),
 ('the', 'DT'),
 ('as', 'IN'),
 ('you', 'PRP'),
 ('with', 'IN'),
 ('out', 'RP'),
 ('themselves', 'PRP'),
 ('powerful', 'JJ'),
 ('lets', 'NNS'),
 ('loves', 'VBZ'),
 ('their', 'PRP$'),
 ('becomes', 'NNS'),
 ('reaching', 'VBG'),
 ('had', 'VBD'),
 ('journalist', 'NN'),
 ('of', 'IN'),
 ('lot', 'NN'),
 ('from', 'IN'),
 ('anyone', 'NN'),
 ('to', 'TO'),
 ('have', 'VB'),
 ('after', 'IN'),
 ('out', 'RP'),
 ('atmosphere', 'RB'),
 ('never', 'RB'),
 ('more', 'JJR'),
 ('room', 'NN'),
 ('titillate', 'NN'),
 ('it', 'PRP'),
 ('so', 'IN'),
 ('heart', 'NN'),
 ('shows', 'VBZ'),
 ('to', 'TO'),
 ('years', 'NNS'),
 ('of', 'IN'),
 ('every', 'DT'),
 ('never', 'RB'),
 ('going', 'VBG'),
 ('villaronga', 'NN'),
 ('help', 'NN'),
 ('moments', 'NNS'),
 ('or', 'CC'),
 ('of', 'IN'),
 ('every', 'DT')]

In [25]:
# Okt # 대문자 클래스 - 인스턴스객체를만들어야한다
k_n=Okt()
k_n.morphs(k_d) #형태소를기준으로단어들만보겟다   여기서단어란명사가 아니라 잘라낸워드를뜻함


['오늘', '은', '인공', '지능', '입니다', '.', '어렵네요', '.']

In [26]:
k_n.pos(k_d) #pos 품사태깅

[('오늘', 'Noun'),
 ('은', 'Josa'),
 ('인공', 'Noun'),
 ('지능', 'Noun'),
 ('입니다', 'Adjective'),
 ('.', 'Punctuation'),
 ('어렵네요', 'Adjective'),
 ('.', 'Punctuation')]

In [27]:
k_n.nouns(k_d) # 명사만 뽑겟다

['오늘', '인공', '지능']

In [29]:
k_n2 = Kkma()
k_n2.morphs(k_d),k_n2.pos(k_d),k_n2.nouns(k_d)

(['오늘', '은', '인공지능', '이', 'ㅂ니다', '.', '어렵', '네요', '.'],
 [('오늘', 'NNG'),
  ('은', 'JX'),
  ('인공지능', 'NNG'),
  ('이', 'VCP'),
  ('ㅂ니다', 'EFN'),
  ('.', 'SF'),
  ('어렵', 'VV'),
  ('네요', 'EFN'),
  ('.', 'SF')],
 ['오늘', '인공', '인공지능', '지능'])

In [30]:
k_n = Okt()
k_n.morphs(k_d),k_n.pos(k_d),k_n.nouns(k_d)

(['오늘', '은', '인공', '지능', '입니다', '.', '어렵네요', '.'],
 [('오늘', 'Noun'),
  ('은', 'Josa'),
  ('인공', 'Noun'),
  ('지능', 'Noun'),
  ('입니다', 'Adjective'),
  ('.', 'Punctuation'),
  ('어렵네요', 'Adjective'),
  ('.', 'Punctuation')],
 ['오늘', '인공', '지능'])

In [ ]:
# 기본적으로 범용적인 Okt 를 쓰자

In [32]:
data = '오늘은 내용이 쉽지는 않군요 그런데 배고파요. 시간은 빠르게 흐르는데 모르겠네요'

In [33]:
불용어 = '은 는 이 가 요 그런데 배고파요'.split()
불용어


['은', '는', '이', '가', '요', '그런데', '배고파요']

In [35]:
okt= Okt()
t_dd = okt.morphs(data)
t_dd

['오늘',
 '은',
 '내용',
 '이',
 '쉽지는',
 '않군요',
 '그런데',
 '배고파요',
 '.',
 '시간',
 '은',
 '빠르게',
 '흐르는데',
 '모르겠네요']

In [37]:
end_d  =  [i for i in t_dd if not i in 불용어]  # 불용어가 아닌 것만 담겠다.
end_d

['오늘', '내용', '쉽지는', '않군요', '.', '시간', '빠르게', '흐르는데', '모르겠네요']

In [114]:
#정규표현식 패키지불러오기
import re # 'd.t' 이건 정규표현식 . 가아니고 그냥문자열이니까 정규표현식패키지가필요

In [41]:
r = re.compile('d.t')  # r 정규표현식장치

In [43]:
r.search('data')      # 일치하는범위를알려줌   한개의임의의문자를일컷는다

<re.Match object; span=(0, 3), match='dat'>

In [44]:
r = re.compile('d?t')  # r 정규표현식장치  # ?는 물음표앞문자 디가잇어도 되고 없어도된다
r.search('dddtt')  #d,t인식                 # t는 기본적으로 잇어야 찾아지고 d는 잇어도되고 없어도된다

<re.Match object; span=(2, 4), match='dt'>

In [63]:
r.search('ddddttttttt')

<re.Match object; span=(3, 5), match='dt'>

In [93]:
r.search('ddddt')

<re.Match object; span=(0, 5), match='ddddt'>

In [92]:
r = re.compile('d*t')            # t는 끝에 잇어야 하고 앞에 d는 무한대로 잇어도 되고 없어도 상관 없다
r.search('dddddt')  #  (0,6) 은 시작부터끝까지 

SyntaxError: ignored

In [91]:
r = re.compile('d*t')
r.search('ttttttt')    

<re.Match object; span=(0, 1), match='t'>

In [90]:
r = re.compile('d+t')  #티 앞에 d가 최소 한개는 잇어야 인식
r.search('ddddddddddttttttt')    

<re.Match object; span=(0, 11), match='ddddddddddt'>

In [95]:
r = re.compile('^ds')  #앞이 ds여야 인식
r.search('ds')    

<re.Match object; span=(0, 2), match='ds'>

In [119]:
data=' ?'
data.replace('^ +','')                 #  ^   뒤의문자열로 문자열이 시작합니다  >  즉 공백으로 시작하는지 보는 표현식
#공백으로 시작하는 것이 맞으니 인식         # [^문자] : 해당문자를제외한문자를매치

' ?'

In [111]:
data=' ?'
r = re.compile('^ ')  
if r.search(data):  # 공백으로시작하는지조건으로걸엇다
    print('실행') 

실행


In [212]:
#특정 변수 앞의 공백을 제거하는 슬라이싱
#정규표현식 패키지불러오기
import re # 'd.t' 이건 정규표현식 . 가아니고 그냥문자열이니까 정규표현식패키지가필요
data=' ?'
r = re.compile('^ ')             #  ^해당문자를제외한
if r.search(data):
    data =data[1:]
data  #0인덱을 날리는 전처리
    

'?'

NameError: ignored

In [ ]:
#데이터프레임에서 시리즈 쭉 뽑아서 앞 공백 없애기  ' ㄴㅇㄹㄴㅇㄹ'

In [ ]:
df['key'] = df.key.str.replace('^ ', '')  # '^ ' 이조건에 맞을 때   ''  이렇게 바꿔준다   #공백으로 시작하는 밸류들은 공백을 없앤다
                            # 공백 1개로 시작하는 걸 찾고 ' ' 공백하나가 조건이니까 뒤에서 '' 하면 딱 맨 앞의 공백 하나만 제거된다 (pd로 확인)
                          # '^ ' 이건 맨 앞이 공백인지 확인하는 조건, ''은 공백을 지운다  
df['key'] = df.key.str.replace('^ ', )   

df['key'] = df.key.str.replace('^ +', ) # 공백이있고 뒤에문자가붙은거 
#데이터프레임에서 시리즈가지고와서 문자에서 대체한다  앞은조건 뒤는 바꿀것


In [250]:
import pandas as pd
b= pd.DataFrame({'key':['abdddd   ', 122,' a','  aa',' a ']})
b

key
0  abdddd   
1        122
2          a
3         aa
4         a

In [251]:
# 시리즈의 각 원소 밸류들을 전부 슬라이싱 할 수 있다
import pandas as pd
b= pd.DataFrame({'key':['abdddd   ', 122,' a','  aa',' a ']})
b
b['key'] = b.key.str[1:3]
b

key
0   bd
1  NaN
2    a
3    a
4   a

In [241]:
import numpy as np
np.unique(b)

TypeError: ignored

In [141]:
b= pd.DataFrame({'key':['a',' a','  aa',' a ']})

b['key'] = b.key.str.replace('^ ', '') 
b

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version.
  This is separate from the ipykernel package so we can avoid doing imports until


key
0    a
1    a
2   aa
3   a

In [142]:
import numpy as np
np.unique(b)

array([' aa', 'a', 'a '], dtype=object)

In [143]:
b['key'][3]

'a '

In [266]:
import pandas as pd
k = pd.DataFrame([' data','da ta','data', '  data' ], columns=['data'])
k

data
0    data
1   da ta
2    data
3    data

In [256]:
k.data  #  = k['data'] 비슷,같은 것

0      data
1     da ta
2      data
3      data
Name: data, dtype: object

In [263]:
k.data.str.replace('^ +', '')[3]  # '^ ' 하면 앞 한 공백만 지우는데 ^ + 하니까  [^ +]문자 여길바꾸니까 앞공백 이어진 것을 전부 지워버린다.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.


'data'

In [253]:
np.unique(k)

array(['  data', ' data', 'da ta', 'data'], dtype=object)

In [255]:
' data'.str.replace('^ +', '')

AttributeError: ignored

In [274]:
k.data.str.replace('^ +' , '')[0]
# k['data'].str같은것

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  """Entry point for launching an IPython kernel.


'data'

In [272]:
'^ + data'.replace('^ +' , '') # 이건 문자정규식이 아니라   ^ + 문자를 지워버린 것

' data'

In [308]:
r = re.compile('asd{2}k')  #중괄호는  2의숫자는 앞의 d를두개로한다는 뜻  asddk와 같은 의미다
r.search('asdk')  #서칭안된다

In [309]:
r = re.compile('asd{2}k')
r.search('asddk')  #서칭 

<re.Match object; span=(0, 5), match='asddk'>

In [310]:
r = re.compile('asd{2,4}k')
r.search('asdddddk')  # d가 두개~4개 까지만 서칭이 된다  2이상 4이하
  

In [311]:
r = re.compile('asd{,2}k')

In [312]:
r = re.compile('asd{2,}k')  # 2개이상 ~무한대

In [ ]:
span()	매치된 문자열의 (시작, 끝)에 해당하는  튜플을 돌려준다.  시작 이상 끝 미만의 인덱스값

In [ ]:
괄호안의문자유무판단  [-]범위를뜻한다


In [336]:
r = re.compile('[abc]')
r.search('edofia')     #  span5,6    5이상 6미만 인덱스에서매ㅣㅇ

<re.Match object; span=(5, 6), match='a'>

In [334]:
r = re.compile('[a-c]') #a부터c까지         #대괄호 안에서는 대괄호 안의 문자 중 앞에서부터 스캔해서 딱 하나랑만 매칭이 된다
r.search('cacdbofi')

<re.Match object; span=(0, 1), match='c'>

In [331]:
r = re.compile('abc') #a부터c까지
r.search('abcc')

<re.Match object; span=(0, 3), match='abc'>

In [330]:
r = re.compile('[a-zA-Z]') #알파벳전부
r.search('aAA')

<re.Match object; span=(0, 1), match='a'>

In [317]:
r = re.compile('[^a-zA-Z]') # 알파벳범위가아닐대 [ ] 안에 ^는다른의미 해당문자를제외한문자
r.search( 'ㅁ')

<re.Match object; span=(0, 1), match='ㅁ'>

In [318]:
r = re.compile('[^ a-zA-Z]') # 알파벳범위가아닐대 [ ] 안에 ^는다른의미 해당문자를제외한문자
r.search( ' ㅁ') #

<re.Match object; span=(1, 2), match='ㅁ'>

In [319]:
r = re.compile('[ a-zA-Z]') # 알파벳범위가아닐대 [ ] 안에 ^는다른의미 해당문자를제외한문자
r.search( ' ㅁ') 

<re.Match object; span=(0, 1), match=' '>

In [320]:
r = re.compile('\s') # 알파벳범위가아닐대 [ ] 안에 ^는다른의미 해당문자를제외한문자
r.search(' ') #?

<re.Match object; span=(0, 1), match=' '>

In [321]:
r = re.compile('\S') # 알파벳범위가아닐대 [ ] 안에 ^는다른의미 해당문자를제외한문자
r.search(' ') #?  # \s긍정 \S부정

In [ ]:
#정규표현식문법 역슬래쉬\ 

In [ ]:
span=(  ) 위치정보

In [ ]:
정규표현식모듈함수

re.compile() 
re.search() 문자열전체를서칭
re.matach() 문자열의처음을서칭
re.split() 정규표현식을기준으로스플릿
re.findall()
re.finditer()
re.sub()


In [ ]:
정수인코딩

In [302]:
from nltk.tokenize import sent_tokenize#문장토큰화
from nltk.tokenize import   word_tokenize #단어토큰화           #영어분석
from nltk.corpus import stopwords #불용어


In [303]:
text = 'A barbar is a person. a barber is good person. a'

In [304]:
문장토큰화_된_data = sent_tokenize(text)
문장토큰화_된_data


['A barbar is a person.', 'a barber is good person.', 'a']

In [ ]:
# 영어는 소문자로 통합 암묵적룰


In [ ]:
#보캐불러리 만들기#

In [306]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
단어모음 = {}
t_data = []
불용성단어 = set(stopwords.words('english')) #영어로구성된불용어모음집가져오기  # 중복안되게 set 으로 받았다
불용성단어 #거를단어

In [ ]:
소문자로만들기

In [351]:
for 문장 in 문장토큰화_된_data:
    단어토큰화_된_data = word_tokenize(문장)
    l=[]
    for 단어 in 단어토큰화_된_data:
        소문자화된_단어 = 단어.lower()  #로어소문자로바꾸기
        if 소문자화된_단어 not in 불용성단어:
            if len(소문자화된_단어) > 2 : #알파벳짧은 것 의미 적을 거니까 배제해보자 2보다 큰 것을 담는다
                aa=l.append(소문자화된_단어)

                if 소문자화된_단어 not in 단어모음: # 단어모음에잇니 #없다면
                    단어모음[소문자화된_단어]= 0
                단어모음[소문자화된_단어]+= 1
                    
    t_data.append(l)
t_data



[['barbar', 'person'],
 ['barber', 'good', 'person'],
 [],
 ['barbar', 'person'],
 ['barber', 'good', 'person'],
 [],
 ['barbar', 'person'],
 ['barber', 'good', 'person'],
 []]

In [344]:
단어모음 #빈도수

{'barbar': 2, 'barber': 2, 'good': 2, 'person': 4}

In [352]:
aa #변수지정x함??

In [348]:
정렬된_단어모음 = sorted(단어모음.items(), key=lambda x:x[1] , reverse = True )  #sorted 나열의기준 키를 같이지정하고싶을떄 솔티드

In [349]:
정렬된_단어모음

[('person', 4), ('barbar', 2), ('barber', 2), ('good', 2)]

In [354]:
단어_인덱스={}   #문자대신 컴퓨터가이해할수잇는숫자로 바꾸기
i=0
for (단어, 빈도수) in 정렬된_단어모음:  #빈도낮은걸 버리겟다 #정~ 딕셔너리
    if 빈도수 > 1: 
        i+=1
        단어_인덱스[단어]=i # 단어를 키값으로 i를 넘버링
단어_인덱스





{'barbar': 2, 'barber': 3, 'good': 4, 'person': 1}

In [355]:
살릴단어수 = 2
제거_data=[단어 for 단어, i in 단어_인덱스.items() if i >살릴단어수 ]  #비중높은것만살리기위해

for i in 제거_data:
    del 단어_인덱스[i]
단어_인덱스

{'barbar': 2, 'person': 1}

In [357]:
단어_인덱스['oov'] = len(단어_인덱스)+1   #oov 아웃오브보캐불러리
단어_인덱스 #어짜피문자는숫자로 단어인덱만잃어버리지않으면 아웃보캐를 가지고잇어도 문제가생기지않는다  단어가없다 단어가스지않는단어
#단어인덱스-보캐불러리만잃지않으면된다 보캐불러리만잇으면 아웃오브보캐를 무시할 수 잇다

{'barbar': 2, 'oov': 3, 'person': 1}

In [358]:
t_data

[['barbar', 'person'],
 ['barber', 'good', 'person'],
 [],
 ['barbar', 'person'],
 ['barber', 'good', 'person'],
 [],
 ['barbar', 'person'],
 ['barber', 'good', 'person'],
 []]

In [359]:
ec_data=[]
for 문장 in t_data:
    ec_d = []
    for 단어 in 문장:
        try: #트라이익셉예외처리   딕셔너리에서 없는 키값을 불러오려고 할 떄 에러가 나기 떄문에 처리하기위함
            ec_d.append(단어_인덱스[단어])
        except KeyError:
            ec_d.append(단어_인덱스['oov'])  # ec_d인코딩된데이터
    ec_data.append(ec_d)
ec_data

# 정수인코딩 끝
    단어를 빈도수 순으로 정렬한 단어집합(vocabulary)을 만들고, 빈도수가 높은 순으로 1번부터 정수를 부여하는 방법
    딕셔너리
    카운터

[[2, 1], [3, 3, 1], [], [2, 1], [3, 3, 1], [], [2, 1], [3, 3, 1], []]

In [ ]:
Counter 기반 정수 인코딩

In [360]:
from collections import Counter

In [362]:
# 토큰화
# 코퍼스 > 문장 > 단어
t_data

[['barbar', 'person'],
 ['barber', 'good', 'person'],
 [],
 ['barbar', 'person'],
 ['barber', 'good', 'person'],
 [],
 ['barbar', 'person'],
 ['barber', 'good', 'person'],
 []]

In [363]:
단어모두모음= sum(t_data,[]) 
단어모두모음

['barbar',
 'person',
 'barber',
 'good',
 'person',
 'barbar',
 'person',
 'barber',
 'good',
 'person',
 'barbar',
 'person',
 'barber',
 'good',
 'person']

In [364]:
end_단어_모음 = Counter(단어모두모음) #단어수세기
end_단어_모음

Counter({'barbar': 3, 'barber': 3, 'good': 3, 'person': 6})

In [365]:
빈도별_단어 = end_단어_모음.most_common(살릴단어수)
빈도별_단어


[('person', 6), ('barbar', 3)]

In [366]:
단어인덱스2 = {}
i=0
for 단어, 빈도수 in 빈도별_단어:
    i+=1
    단어인덱스2[단어]=i
단어인덱스2

{'barbar': 2, 'person': 1}

In [367]:
단어인덱스2['oov'] = len(단어인덱스2)+1   #oov 아웃오브보캐불러리
단어인덱스2 

{'barbar': 2, 'oov': 3, 'person': 1}

In [368]:
ec_data2=[]
for 문장 in t_data:
    ec_d = []
    for 단어 in 문장:
        try: #트라이익셉예외처리   딕셔너리에서 없는 키값을 불러오려고 할 떄 에러가 나기 떄문에 처리하기위함
            ec_d.append(단어인덱스2[단어])
        except KeyError:
            ec_d.append(단어인덱스2['oov'])  # ec_d인코딩된데이터
    ec_data2.append(ec_d)
ec_data2


[[2, 1], [3, 3, 1], [], [2, 1], [3, 3, 1], [], [2, 1], [3, 3, 1], []]

In [ ]:
영어 nltk 정수인코딩

In [370]:
from nltk import FreqDist
import numpy as np
t_data

[['barbar', 'person'],
 ['barber', 'good', 'person'],
 [],
 ['barbar', 'person'],
 ['barber', 'good', 'person'],
 [],
 ['barbar', 'person'],
 ['barber', 'good', 'person'],
 []]

In [372]:
np.hstack(t_data) #에이치스택 - 모음집

array(['barbar', 'person', 'barber', 'good', 'person', 'barbar', 'person',
       'barber', 'good', 'person', 'barbar', 'person', 'barber', 'good',
       'person'], dtype='<U32')

In [380]:
단어_모음집 = FreqDist(np.hstack(t_data)) #빈도수
단어_모음집 


FreqDist({'barbar': 3, 'barber': 3, 'good': 3, 'person': 6})

In [381]:
결과_단어_모음집 = 단어_모음집.most_common(살릴단어수)
결과_단어_모음집 

[('person', 6), ('barbar', 3)]

In [ ]:
데이터전처리

In [382]:
from tensorflow.keras.preprocessing.text import Tokenizer #토크나이저클래스  를가지고보캐불러리를만들겟다


In [383]:
ck_t = Tokenizer()
ck_t.fit_on_texts(t_data)
print(ck_t.word_index)
print(ck_t.word_counts)

{'person': 1, 'barbar': 2, 'barber': 3, 'good': 4}
OrderedDict([('barbar', 3), ('person', 6), ('barber', 3), ('good', 3)])


In [ ]:
tr_data = ck_t.text_to_word_sequence(t_data)  # 트랜스퍼
tr_data #보캐불러리

In [384]:
살릴단어수 # 두개빼고는 전부 아웃오브보캐로 뺴겟다는 

2

In [ ]:
test = Tokenizer(num_words=살릴단어수)

num_words=None, #내가사용한문자에대한내용
filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',   #특수문자제거하라는것
lower=True, #소문자
split=' ', 
char_level=False, 
oov_token=None, #토큰쓸거니
document_count=0,
 **kwargs)

In [ ]:
토크나이저를 쓸 때 살릴단어수에서 하나는 oov로바찐다     (넘워드=살릴단어+1) #<이걸로사용
                                                          (넘워드=살릴단어+2, 아웃오버보캐=)
#매개변수로아웃오버보캐를넣을때
#살릴단어수가4면 3까지만뽑힌다 그런데 0값은 자동으로 날리기 떄문에 2까지만 뽑힌다
 # 즉 살릴단어수+2 를 입력해야한다

토크나이저쓰면 인덱스붙는다

In [ ]:
# 케라스 전처리기 이용 정리
# 데이터수집(코퍼스수집)

In [385]:
text = "A barber is a person. a barber is good person. a barber is huge person. he Knew A Secret! The Secret He Kept is huge secret. Huge secret. His barber kept his word. a barber kept his word. His barber kept his secret. But keeping and keeping such a huge secret to himself was driving the barber crazy. the barber went up a huge mountain."

In [ ]:
#토큰화

In [395]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence #<토크나이저??;토큰화;잘라주는
from nltk.tokenize import word_tokenize # 토크나이저
from nltk.tokenize import WordPunctTokenizer #토크나이저
from nltk.corpus import stopwords


In [396]:


nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [397]:
문장토큰화_된_data = sent_tokenize(text)
문장토큰화_된_data


['A barber is a person.',
 'a barber is good person.',
 'a barber is huge person.',
 'he Knew A Secret!',
 'The Secret He Kept is huge secret.',
 'Huge secret.',
 'His barber kept his word.',
 'a barber kept his word.',
 'His barber kept his secret.',
 'But keeping and keeping such a huge secret to himself was driving the barber crazy.',
 'the barber went up a huge mountain.']

In [398]:
단어모음 = {}
t_data = []
불용성단어 = set(stopwords.words('english')) #영어로구성된불용어모음집가져오기  # 중복안되게 set 으로 받았다
불용성단어 #거를단어

for 문장 in 문장토큰화_된_data:
    단어토큰화_된_data = word_tokenize(문장)
    l=[]
    for 단어 in 단어토큰화_된_data:
        소문자화된_단어 = 단어.lower()  #로어소문자로바꾸기
        if 소문자화된_단어 not in 불용성단어:
            if len(소문자화된_단어) > 2 : #알파벳짧은 것 의미 적을 거니까 배제해보자 2보다 큰 것을 담는다
                aa=l.append(소문자화된_단어)

                if 소문자화된_단어 not in 단어모음: # 단어모음에잇니 #없다면
                    단어모음[소문자화된_단어]= 0
                단어모음[소문자화된_단어]+= 1
                    
    t_data.append(l)
t_data



[['barber', 'person'],
 ['barber', 'good', 'person'],
 ['barber', 'huge', 'person'],
 ['knew', 'secret'],
 ['secret', 'kept', 'huge', 'secret'],
 ['huge', 'secret'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'word'],
 ['barber', 'kept', 'secret'],
 ['keeping', 'keeping', 'huge', 'secret', 'driving', 'barber', 'crazy'],
 ['barber', 'went', 'huge', 'mountain']]

In [ ]:
정수인코딩

In [399]:
from tensorflow.keras.preprocessing.text import Tokenizer
tk= Tokenizer()
tk.fit_on_texts(t_data)
ec_data = tk.texts_to_sequences(t_data)
ec_data

[[1, 5],
 [1, 8, 5],
 [1, 3, 5],
 [9, 2],
 [2, 4, 3, 2],
 [3, 2],
 [1, 4, 6],
 [1, 4, 6],
 [1, 4, 2],
 [7, 7, 3, 2, 10, 1, 11],
 [1, 12, 3, 13]]

In [ ]:
패딩

In [405]:
from tensorflow.keras.preprocessing.sequence import pad_sequences #패딩
ec_data #인코딩된데이터
end_data = pad_sequences(ec_data)
end_data

array([[ 0,  0,  0,  0,  0,  1,  5],
       [ 0,  0,  0,  0,  1,  8,  5],
       [ 0,  0,  0,  0,  1,  3,  5],
       [ 0,  0,  0,  0,  0,  9,  2],
       [ 0,  0,  0,  2,  4,  3,  2],
       [ 0,  0,  0,  0,  0,  3,  2],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  6],
       [ 0,  0,  0,  0,  1,  4,  2],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 0,  0,  0,  1, 12,  3, 13]], dtype=int32)

In [401]:
end_data = pad_sequences (ec_data, padding = 'post')  # 0을 뒤쪽으로 채우는 패딩
end_data

array([[ 1,  5,  0,  0,  0,  0,  0],
       [ 1,  8,  5,  0,  0,  0,  0],
       [ 1,  3,  5,  0,  0,  0,  0],
       [ 9,  2,  0,  0,  0,  0,  0],
       [ 2,  4,  3,  2,  0,  0,  0],
       [ 3,  2,  0,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  6,  0,  0,  0,  0],
       [ 1,  4,  2,  0,  0,  0,  0],
       [ 7,  7,  3,  2, 10,  1, 11],
       [ 1, 12,  3, 13,  0,  0,  0]], dtype=int32)

In [402]:
end_data = pad_sequences (ec_data, padding = 'post', maxlen=4)  # 0을 뒤쪽으로 채우는 패딩
end_data                 #지우는 것도 채우는 것도 앞에서부터다 기본값이            7 7 73 이 없어진것을보면알수잇다

# 순환신경망. 앞/ 단기기억/ 앞에가 지워지니가   앞에서 채운다
# 지우는 관점에선 미괄식

array([[ 1,  5,  0,  0],
       [ 1,  8,  5,  0],
       [ 1,  3,  5,  0],
       [ 9,  2,  0,  0],
       [ 2,  4,  3,  2],
       [ 3,  2,  0,  0],
       [ 1,  4,  6,  0],
       [ 1,  4,  6,  0],
       [ 1,  4,  2,  0],
       [ 2, 10,  1, 11],
       [ 1, 12,  3, 13]], dtype=int32)

In [407]:
end_data = pad_sequences (ec_data, padding = 'post',truncating='post', maxlen=4)  # 0을 뒤쪽으로 채우는 패딩
end_data                # 이건 뒤에서 지워진다

array([[ 1,  5,  0,  0],
       [ 1,  8,  5,  0],
       [ 1,  3,  5,  0],
       [ 9,  2,  0,  0],
       [ 2,  4,  3,  2],
       [ 3,  2,  0,  0],
       [ 1,  4,  6,  0],
       [ 1,  4,  6,  0],
       [ 1,  4,  2,  0],
       [ 7,  7,  3,  2],
       [ 1, 12,  3, 13]], dtype=int32)

In [403]:
end_data = pad_sequences(ec_data, maxlen=4)
end_data

array([[ 0,  0,  1,  5],
       [ 0,  1,  8,  5],
       [ 0,  1,  3,  5],
       [ 0,  0,  9,  2],
       [ 2,  4,  3,  2],
       [ 0,  0,  3,  2],
       [ 0,  1,  4,  6],
       [ 0,  1,  4,  6],
       [ 0,  1,  4,  2],
       [ 2, 10,  1, 11],
       [ 1, 12,  3, 13]], dtype=int32)

In [409]:
 
end_data = pad_sequences (ec_data, padding = 'post', maxlen=4, value=3)  # 0대신 3을 넣는다 
end_data           


array([[ 1,  5,  3,  3],
       [ 1,  8,  5,  3],
       [ 1,  3,  5,  3],
       [ 9,  2,  3,  3],
       [ 2,  4,  3,  2],
       [ 3,  2,  3,  3],
       [ 1,  4,  6,  3],
       [ 1,  4,  6,  3],
       [ 1,  4,  2,  3],
       [ 2, 10,  1, 11],
       [ 1, 12,  3, 13]], dtype=int32)

In [410]:
v=len(tk.word_index)+1 # 아웃오브보캐로 채워지는
#없으니까패딩으로스겟다
end_data = pad_sequences (ec_data, padding = 'post', maxlen=4, value= v)  # 0대신 v을 넣는다 
end_data           

# > 그냥 0 으로 쓰세요 value날려

array([[ 1,  5, 14, 14],
       [ 1,  8,  5, 14],
       [ 1,  3,  5, 14],
       [ 9,  2, 14, 14],
       [ 2,  4,  3,  2],
       [ 3,  2, 14, 14],
       [ 1,  4,  6, 14],
       [ 1,  4,  6, 14],
       [ 1,  4,  2, 14],
       [ 2, 10,  1, 11],
       [ 1, 12,  3, 13]], dtype=int32)

In [ ]:
한글관점

In [413]:
k_data = '오늘은 시간이 빠르게 가네요'
from tensorflow.keras.preprocessing.text import Tokenizer
k_tk=Tokenizer()
# k_tk.fit_on_texts(k_data)  #코퍼스를 전달받는다 코퍼스는 이차원 ㄷ
k_tk.fit_on_texts([k_data]) #차원을하나올려버리면단어로받는다
k_tk.index_word

{1: '오늘은', 2: '시간이', 3: '빠르게', 4: '가네요'}

In [416]:
txt = '오늘은 이상하게 피곤 하네요 그런데 시간은 느리게 가네요'
#보캐입장에선 입력안받ㄴ은데이터는 없는단어로 인식

k_tk.texts_to_sequences([txt])[0]
# txt랑 k_tk랑 겹치는 부분이 오늘은 이랑 가네요 두개다 그 인덱스가 1과 4이다
#보캐를 만들ㄷ려고 토큰화작업을 하는 것이다



#아웃풋에원핫거는건 분류할 떄 카~

[1, 4]

In [ ]:
패딩:병렬연산을위해여러문장의길이를임의로동일하게맞춰주는작업
>
원핫

투카테원핫 차원이많이늘어난다  > 차원의저주/소실  > 벡터화-임베딩 작은차원

In [ ]:
언어모델이란:이전단어로다음단어를예측
    통계를이용한방법과인공신경망을이용한방법 / 최근에는인공신경망성능이좋음


In [ ]:
# 통계기반모델       

유니그램
i        am         a            boy           n-1과 n값을 비교하여 확률을 연산

바이그램
i am            am a             a boy
엔그램
i am a            am a boy

엔그램의한계
    희소문제
        충분한데이터를관측하지못하여언어를정확히모델링하지못하는문제

조건부확률/ 유니그램 바이그램 엔그램

In [ ]:
단어표현
    워드투백 Word2Vec  단어를 벡터로 바꾸겠다는뜻 차원에 단어를 뿌리는 방법
